name: Basic CI

on:
  push:
    branches:
      - main
    paths:
      - "**.js"
      - "package.json"
      - "package-lock.json"
  pull_request:
    branches:
      - main
    paths:
      - "**.js"
      - "package.json"
      - "package-lock.json"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node-version: [18, 20, 22]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm install
      - run: npm test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - run: npm install

      - name: Run build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist/
      - name: Debug dist folder
        run: ls -R

  deploy:
    runs-on: ubuntu-latest
    needs: [test, build]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Show deployed files
        run: ls -R

      - name: Simuate deployment
        run: cat output.txt

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Build docker image
        run: docker build -t ci-cd-app .
