name: Basic CI

on:
  push:
    branches:
      - main
    paths:
      - "**.js"
      - "package.json"
      - "package-lock.json"
  pull_request:
    branches:
      - main
    paths:
      - "**.js"
      - "package.json"
      - "package-lock.json"

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        node-version: [18, 20, 22]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - run: npm install
      - run: npm test

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - run: npm install

      - name: Run build
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: dist/
      - name: Debug dist folder
        run: ls -R

  deploy:
    runs-on: ubuntu-latest
    needs: [test, build]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-output

      - name: Show deployed files
        run: ls -R

      - name: Simuate deployment
        run: cat output.txt

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and tag image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ci-cd-app:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/ci-cd-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/ci-cd-app:latest

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/ci-cd-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/ci-cd-app:latest

  integration:
    runs-on: ubuntu-latest
    needs: docker

    services:
      mongo:
        image: mongo:6
        ports:
          - 27017:27017

    steps:
      - uses: actions/checkout@v4

      - name: Run app container
        run: |
          docker run -d --name app \
            --network host \
            ${{ secrets.DOCKER_USERNAME }}/ci-cd-app:${{ github.sha }}

      - name: Wait for app
        run: sleep 5

      - name: Test endpoint
        run: curl http://localhost:3000
